@ -0,0 +1,28 @@
set_property PACKAGE_PIN U14 [get_ports A]
set_property PACKAGE_PIN V13 [get_ports B]
set_property PACKAGE_PIN T12 [get_ports SW]
set_property PACKAGE_PIN N18 [get_ports clk]
set_property PACKAGE_PIN L16 [get_ports {globalCount[0]}]
set_property PACKAGE_PIN H15 [get_ports {globalCount[1]}]
set_property PACKAGE_PIN F16 [get_ports {globalCount[2]}]
set_property PACKAGE_PIN E18 [get_ports {globalCount[3]}]
set_property PACKAGE_PIN B19 [get_ports {globalCount[4]}]
set_property PACKAGE_PIN D19 [get_ports {globalCount[5]}]
set_property PACKAGE_PIN E17 [get_ports {globalCount[6]}]
set_property PACKAGE_PIN H16 [get_ports {globalCount[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports SW]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {globalCount[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]

